# Generated by Django 5.2.3 on 2025-08-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='building_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='repair_status',
            field=models.CharField(max_length=35, verbose_name='Repair Status'),
        ),
    ]
