# Generated by Django 5.2.3 on 2025-06-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_announcement_repair_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='commission_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Amount'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='commission_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Bonus'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='commission_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Percentage'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='commission_type',
            field=models.CharField(choices=[('seller', 'Я беру с продавца, вы берете с покупателя'), ('split', 'Я беру с продавца и % с покупателя'), ('buyer', 'Я беру с продавца, вы - с покупателя + доплата')], default=1, max_length=20, verbose_name='Commission Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='krisha_link',
            field=models.URLField(blank=True, null=True, verbose_name='Krisha.kz Link'),
        ),
    ]
