# Generated by Django 5.2.3 on 2025-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_first_login_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='landmark',
            field=models.CharField(blank=True, choices=[('', 'Не выбрано'), ('central_mosque', 'Центральная (Новая) Мечеть'), ('expo_mega', 'ЭКСПО и ТРЦ "MEGA Silkway"'), ('nazarbayev_university', 'Назарбаев Университет'), ('ellington_mall', 'ТРК "Эллингтон Молл"'), ('barys_astana_arena', 'Барыс Арена и Астана Арена'), ('botanical_garden', 'Ботанический сад'), ('sphere_park', 'Сфера Парк'), ('presidential_park_left', 'Президентский парк (Левый берег)'), ('presidential_park_right', 'Президентский парк (Правый берег)'), ('khan_shatyr', 'Хан Шатыр'), ('abu_dhabi_baiterek', 'Абу Даби Плаза и Байтерек'), ('central_park', 'Центральный парк'), ('pyramid', 'Пирамида'), ('new_station', 'Новый вокзал'), ('triathlon_park', 'Триатлон Парк'), ('meeting_center', 'ТЦ "Встреча"'), ('eurasia_mall', 'ТРЦ "Евразия"'), ('akimat_museum', 'Здание акимата (Музей первого Президента)'), ('koktal_park', 'Парк "Коктал"'), ('artem_market', 'Рынок Артём'), ('old_station', 'Старый вокзал'), ('central_embankment', 'Центральная набережная')], max_length=50, null=True, verbose_name='Landmark'),
        ),
    ]
