# Generated by Django 5.2.3 on 2025-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_populate_landmarks'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landmarks (
                    id SERIAL PRIMARY KEY,
                    code VARCHAR(50) UNIQUE NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landmarks;"
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='landmark',
        ),
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS main_announcement_landmarks (
                    id SERIAL PRIMARY KEY,
                    announcement_id INTEGER REFERENCES announcements(id) ON DELETE CASCADE,
                    landmark_id INTEGER REFERENCES landmarks(id) ON DELETE CASCADE,
                    UNIQUE(announcement_id, landmark_id)
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS main_announcement_landmarks;"
        ),
    ]
