# Generated by Django 5.2.3 on 2025-07-13 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_buildingtype_landmark_microdistrict_repairtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('view_page', 'Просмотр страницы'), ('create_announcement', 'Создание объявления'), ('edit_announcement', 'Редактирование объявления'), ('delete_announcement', 'Удаление объявления'), ('archive_announcement', 'Архивирование объявления'), ('unarchive_announcement', 'Восстановление объявления'), ('view_announcement', 'Просмотр объявления'), ('search_announcements', 'Поиск объявлений'), ('filter_announcements', 'Фильтрация объявлений'), ('create_collection', 'Создание коллекции'), ('edit_collection', 'Редактирование коллекции'), ('delete_collection', 'Удаление коллекции'), ('add_to_collection', 'Добавление в коллекцию'), ('remove_from_collection', 'Удаление из коллекции'), ('view_collection', 'Просмотр коллекции'), ('upload_photo', 'Загрузка фото'), ('delete_photo', 'Удаление фото'), ('set_main_photo', 'Установка главного фото'), ('upload_user_photo', 'Загрузка фото профиля'), ('update_profile', 'Обновление профиля'), ('view_profile', 'Просмотр профиля'), ('change_password', 'Изменение пароля'), ('export_data', 'Экспорт данных'), ('api_call', 'API запрос'), ('error', 'Ошибка')], max_length=50, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии')),
                ('page_url', models.URLField(blank=True, null=True, verbose_name='URL страницы')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Referrer')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('related_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.announcement', verbose_name='Связанное объявление')),
                ('related_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.collection', verbose_name='Связанная коллекция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активность пользователей',
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='user_activi_user_id_d06d90_idx'), models.Index(fields=['action_type'], name='user_activi_action__ed5d9e_idx'), models.Index(fields=['timestamp'], name='user_activi_timesta_12eff7_idx')],
            },
        ),
    ]
