# Generated by Django 5.2.3 on 2025-07-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250714_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='commission_percentage',
        ),
    ] 