# Generated by Django 5.2.3 on 2025-07-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_commission_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Landmark',
                'verbose_name_plural': 'Landmarks',
                'db_table': 'landmarks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='commission_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Percentage'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='landmarks',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='main.landmark', verbose_name='Landmarks'),
        ),
    ]
